# Page settings
baseurl = ""
title = "Emma-Alv"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = ""
  email = ""

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = ""

  # Navigation
  [params.navigation]
    brand = "Emma-Alv"
    home = "Home"
    work = "Work"
    about = "About"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "Emmanuel Rodriguez Alvarado."
    subtitle = 'Computer Technologies in Telecommunications'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  # [params.intro]
    enable = false

  # [[params.intro.item]]
    # title = "Plan"
    # description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    # url = "#"
    # button = "Get In Touch"
    # icon = "icon-bulb"
    # img = "img_7.jpg"

  # [[params.intro.item]]
    # title = "Develop"
    # description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    # url = "#"
    # button = "Click Me"
    # icon = "icon-wrench"
    # img = "img_8.jpg"

  # [[params.intro.item]]
    # title = "Launch"
    # description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    # url = "#"
    # button = "Why us?"
    # icon = "icon-rocket"
    # img = "img_10.jpg"


  # [params.intro.video]
    # enable = true
    # title = "Watch the video"
    # icon = "icon-play2"
    # url = "https://vimeo.com/channels/staffpicks/93951774"


  # Work section
  [params.work]
    enable = true
    title = "Work"
    description = "Here you can see some of my previous works."

    [[params.work.row]]
      img = "work_1.png"
      alt = "Image2"
      title = "Matrix operation distributed"
      subtitle = "https://emma-alv.github.io/411-W14/"

    [[params.work.row]]
      img = "work_2.png"
      alt = "Image2"
      title = "Matrix exponential"
      subtitle = "https://emma-alv.github.io/Week14/"

    [[params.work.row]]
      img = "work_3.png"
      alt = "Image3"
      title = "Ping Statistics"
      subtitle = "https://emma-alv.github.io/ping_statistics/"

  # Services section
  [params.services]
    enable = false
    title = "Services"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.services.item]]
      title = "Brand &amp; Strategy"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-anchor"

    [[params.services.item]]
      title = "Web &amp; Interface"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-layers2"
    [[params.services.item]]
      title = "Photo &amp; Video"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-video2"

      [[params.services.item]]
      title = "CMS &amp; eCommerce"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"      
      icon = "icon-monitor"

  # About section
  [params.about]
    enable = true
    title = "About"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.about.item]]
      name = "Emmanuel Rodriguez Alvarado"
      position = "Software Developer"
      description = "For the last year, I have been working at some projects, academic and professional, as a developer. My current experience is related to Python and R programming, developing solutions for Cloud Services, Big Data and Distributed Systems "
      img = "emm_alv.jpg"
      alt = "Person1"
      social = [
        ["icon-twitter", "https://twitter.com/emma_rodalv"],
        ["icon-linkedin", "https://www.linkedin.com/in/erodrigueza/"],
        ["icon-github", "https://emma-alv.github.io"]
      ]

  # Contact section
  [params.contact]
    enable = true
    map = false
    form = true
    title = "Get in touch"
    description = "If you want to colaborate with you at any project, just contact me."
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Riga, Latvia"],
        ["icon-phone", "+371 (26) 555 555"],
        ["icon-envelope", "emm.rod.alv@gmail.com"],
        ["icon-globe", '<a href="http://emma-alv.com" target="_blank">emma-alv.com</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Elate Free HTML5. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'
    links = [
        ["icon-twitter", "https://twitter.com/emma_rodalv"],
        ["icon-linkedin", "https://www.linkedin.com/in/erodrigueza/"],
        ["icon-github", "https://emma-alv.github.io"]
      ]
